### ISSUE TITLE
cannot load embed: malformed module path "embed": missing dot in first path element

### ISSUE THREAD

**Issue by Gys** [wolfeidau/hotwire-golang-website#3]
Hi!

If I run `make start` then I get this error:

    ...
    go: finding golang.org/x/text v0.3.3
    go: finding github.com/rs/zerolog v1.20.0
    go: finding github.com/wolfeidau/echo-middleware v1.1.0
    build command-line-arguments: cannot load embed: malformed module path "embed": missing dot in first path element
    make: *** [start] Error 1

Any idea why this fails?

**Comment by wolfeidau** [comment]
@Gys you need to have Go 1.16 RC1 installed to run this at the moment.

Given I am only using this in ONE place https://github.com/wolfeidau/hotwire-golang-website/blob/master/views/views.go#L7 I should go back to the stable way.

Will do a PR later to fix this.

**Comment by wolfeidau** [comment]
@Gys turns out it was a quick fix to remove so done 🎉 

I should know that publishing an example site using unreleased stuff would be unwise 😅

**Comment by Gys** [comment]
I am still on go 1.13.15 so that explains it.
Thanks for the update! Works now.
